export const ErrorCodes = {
    TRANSACTION_FAILED: 'TRANSACTION_FAILED',
    INITIALIZATION_FAILED: 'INITIALIZATION_FAILED',
    QUERY_FAILED: 'QUERY_FAILED',
    DATA_TYPE_MISMATCH: 'DATA_TYPE_MISMATCH',
    COLUMN_NOT_FOUND: 'COLUMN_NOT_FOUND',
    TABLE_NOT_FOUND: 'TABLE_NOT_FOUND',
    INVALID_SCHEMA: 'INVALID_SCHEMA'
};
